version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: alexmacniven/get-started:part2
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
networks:
  webnet:

# Runs alexmacniven/get-started:part2
# Runs 5 instances in a service called 'web'
# Each instance capped at 10%CPU and 50MB
# Containers will restart on failure
# LocalHost:4000 mapped to Exposed port 80
# Containers share port 80 on load-balanced network called 'webnet'
# 'webnet' network uses default config